// core
export const LOADING = 'LOADING'
export const ERROR = 'ERROR'
// home
export const LOAD_ALL_CATEGORIES = 'LOAD_ALL_CATEGORIES'
export const LOAD_ALL_HOME_VIDEO = 'LOAD_ALL_HOME_VIDEO'
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'

// history
export const LOAD_HISTORY = 'LOAD_HISTORY'
export const REMOVE_WATCH_HISTORY = 'REMOVE_WATCH_HISTORY'
export const ADD_TO_WATCH_HISTORY = 'ADD_TO_WATCH_HISTORY'
export const REMOVE_ALL_HISTORY = 'REMOVE_ALL_HISTORY'
// watchlater
export const LOAD_WATCH_LATER = 'LOAD_WATCH_LATER'
export const ADD_TO_WATCH_LATER = 'ADD_TO_WATCH_LATER'
export const REMOVE_WATCH_LATER = 'REMOVE_WATCH_LATER'
//like
export const LOAD_LIKE = 'LOAD_LIKE'
export const ADD_LIKE = 'ADD_LIKE'
export const REMOVE_LIKE = 'REMOVE_LIKE'
// auth
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const SAVE_USER_INFO = 'SAVE_USER_INFO'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOG_OUT = 'LOG_OUT'
// playlist 
export const GET_PLAYLISTS = 'GET_PLAYLISTS'
export const ADD_PLAYLIST = 'ADD_PLAYLIST'
export const REMOVE_PLAYLIST = 'REMOVE_PLAYLIST'
// playlist video
export const ADD_VIDEO_TO_PLAYLIST = 'ADD_VIDEO_TO_PLAYLIST'
export const REMOVE_VIDEO_FROM_PLAYLIST = 'REMOVE_VIDEO_FROM_PLAYLIST'
export const GET_VIDEO_FOR_PLAYLIST = 'GET_VIDEO_FOR_PLAYLIST'
